### ISSUE TITLE
Refatorar Usando DTO de resposta

### ISSUE THREAD

**Issue by hemilioaraujo** [hemilioaraujo/mentoria#22]
### Funcionário
- [x] adicionar RespostaDTO no service
- [x] corrigir erros
- [x] ajustar controller para receber RespostaDTO

### Tutor
- [ ] adicionar RespostaDTO no service
- [ ] corrigir erros
- [ ] ajustar controller para receber RespostaDTO

### Serviço
- [ ] adicionar RespostaDTO no service
- [ ] corrigir erros
- [ ] ajustar controller para receber RespostaDTO

### Agendamento
- [ ] adicionar RespostaDTO no service
- [ ] corrigir erros
- [ ] ajustar controller para receber RespostaDTO

### Todos
- [x] agrupar rotas
